spring:
    application:
        name: trablho-prog-web

    datasource:
        url: jdbc:h2:mem:trabalho
        driverClassName: org.h2.Driver
        username: sa
        password: root

    h2:
        console:
            enabled: true
            path: /h2-console

    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
